name: Validate Shell Script

on:
  push:
    branches:
      - main  # Se ejecutar치 solo cuando se haga un push a la rama principal (main)

jobs:
  shellcheck:
    runs-on: ubuntu-latest  # El flujo de trabajo se ejecutar치 en un entorno Ubuntu

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Esto asegura que el repositorio se descargue en el runner de GitHub Actions

      - name: Install ShellCheck
        run: sudo apt-get install -y shellcheck  # Instala el comando shellcheck en el runner

      - name: Run ShellCheck on script.sh
        run: shellcheck script.sh  # Ejecuta shellcheck sobre el archivo script.sh

      - name: Fail if ShellCheck finds issues
        if: ${{ failure() }}
        run: |
          echo "ShellCheck found issues in the script!"
          exit 1  # Si shellcheck encuentra errores, el flujo de trabajo fallar치 y notificar치 el error
